function [fitresult, gof] = createFits4(cdate, pop)
%CREATEFITS4(CDATE,POP)
%  Create fits.
%
%  Data for 'poly2' fit:
%      X Input : cdate
%      Y Output: pop
%  Data for 'poly3' fit:
%      X Input : cdate
%      Y Output: pop
%  Data for 'poly4' fit:
%      X Input : cdate
%      Y Output: pop
%  Data for 'poly5' fit:
%      X Input : cdate
%      Y Output: pop
%  Data for 'poly6' fit:
%      X Input : cdate
%      Y Output: pop
%  Data for 'exp2' fit:
%      X Input : cdate
%      Y Output: pop
%  Output:
%      fitresult : a cell-array of fit objects representing the fits.
%      gof : structure array with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 14-Mar-2022 19:01:34

%% Initialization.

% Initialize arrays to store fits and goodness-of-fit.
fitresult = cell( 6, 1 );
gof = struct( 'sse', cell( 6, 1 ), ...
    'rsquare', [], 'dfe', [], 'adjrsquare', [], 'rmse', [] );

%% Fit: 'poly2'.
[xData, yData] = prepareCurveData( cdate, pop );

% Set up fittype and options.
ft = fittype( 'poly2' );

% Fit model to data.
[fitresult{1}, gof(1)] = fit( xData, yData, ft, 'Normalize', 'on' );

% Create a figure for the plots.
figure( 'Name', 'poly2' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult{1}, xData, yData );
legend( h, 'pop vs. cdate', 'poly2', 'Location', 'NorthEast' );
% Label axes
xlabel cdate
ylabel pop
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult{1}, xData, yData, 'residuals' );
legend( h, 'poly2 - residuals', 'Zero Line', 'Location', 'NorthEast' );
% Label axes
xlabel cdate
ylabel pop
grid on

%% Fit: 'poly3'.
[xData, yData] = prepareCurveData( cdate, pop );

% Set up fittype and options.
ft = fittype( 'poly3' );

% Fit model to data.
[fitresult{2}, gof(2)] = fit( xData, yData, ft, 'Normalize', 'on' );

% Create a figure for the plots.
figure( 'Name', 'poly3' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult{2}, xData, yData );
legend( h, 'pop vs. cdate', 'poly3', 'Location', 'NorthEast' );
% Label axes
xlabel cdate
ylabel pop
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult{2}, xData, yData, 'residuals' );
legend( h, 'poly3 - residuals', 'Zero Line', 'Location', 'NorthEast' );
% Label axes
xlabel cdate
ylabel pop
grid on

%% Fit: 'poly4'.
[xData, yData] = prepareCurveData( cdate, pop );

% Set up fittype and options.
ft = fittype( 'poly4' );

% Fit model to data.
[fitresult{3}, gof(3)] = fit( xData, yData, ft, 'Normalize', 'on' );

% Create a figure for the plots.
figure( 'Name', 'poly4' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult{3}, xData, yData );
legend( h, 'pop vs. cdate', 'poly4', 'Location', 'NorthEast' );
% Label axes
xlabel cdate
ylabel pop
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult{3}, xData, yData, 'residuals' );
legend( h, 'poly4 - residuals', 'Zero Line', 'Location', 'NorthEast' );
% Label axes
xlabel cdate
ylabel pop
grid on

%% Fit: 'poly5'.
[xData, yData] = prepareCurveData( cdate, pop );

% Set up fittype and options.
ft = fittype( 'poly5' );

% Fit model to data.
[fitresult{4}, gof(4)] = fit( xData, yData, ft, 'Normalize', 'on' );

% Create a figure for the plots.
figure( 'Name', 'poly5' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult{4}, xData, yData );
legend( h, 'pop vs. cdate', 'poly5', 'Location', 'NorthEast' );
% Label axes
xlabel cdate
ylabel pop
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult{4}, xData, yData, 'residuals' );
legend( h, 'poly5 - residuals', 'Zero Line', 'Location', 'NorthEast' );
% Label axes
xlabel cdate
ylabel pop
grid on

%% Fit: 'poly6'.
[xData, yData] = prepareCurveData( cdate, pop );

% Set up fittype and options.
ft = fittype( 'poly6' );

% Fit model to data.
[fitresult{5}, gof(5)] = fit( xData, yData, ft, 'Normalize', 'on' );

% Create a figure for the plots.
figure( 'Name', 'poly6' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult{5}, xData, yData );
legend( h, 'pop vs. cdate', 'poly6', 'Location', 'NorthEast' );
% Label axes
xlabel cdate
ylabel pop
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult{5}, xData, yData, 'residuals' );
legend( h, 'poly6 - residuals', 'Zero Line', 'Location', 'NorthEast' );
% Label axes
xlabel cdate
ylabel pop
grid on

%% Fit: 'exp2'.
[xData, yData] = prepareCurveData( cdate, pop );

% Set up fittype and options.
ft = fittype( 'exp2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Normalize = 'on';
opts.StartPoint = [35.325586963032 1.33744935362671 0 1.33744935362671];

% Fit model to data.
[fitresult{6}, gof(6)] = fit( xData, yData, ft, opts );

% Create a figure for the plots.
figure( 'Name', 'exp2' );

% Plot fit with data.
subplot( 2, 1, 1 );
h = plot( fitresult{6}, xData, yData );
legend( h, 'pop vs. cdate', 'exp2', 'Location', 'NorthEast' );
% Label axes
xlabel cdate
ylabel pop
grid on

% Plot residuals.
subplot( 2, 1, 2 );
h = plot( fitresult{6}, xData, yData, 'residuals' );
legend( h, 'exp2 - residuals', 'Zero Line', 'Location', 'NorthEast' );
% Label axes
xlabel cdate
ylabel pop
grid on


