function [fitresult, gof] = createFit(cdate, pop)
%CREATEFIT(CDATE,POP)
%  Create a fit.
%
%  Data for 'poly6' fit:
%      X Input : cdate
%      Y Output: pop
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 14-Mar-2022 20:52:48


%% Fit: 'poly6'.
[xData, yData] = prepareCurveData( cdate, pop );

% Set up fittype and options.
ft = fittype( 'poly6' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, 'Normalize', 'on' );

% Plot fit with data.
figure( 'Name', 'poly6' );
h = plot( fitresult, xData, yData );
legend( h, 'pop vs. cdate', 'poly6', 'Location', 'NorthEast' );
% Label axes
xlabel cdate
ylabel pop
grid on


